# Generated by Django 5.2.11 on 2026-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_style', models.CharField(choices=[('why_it_matters', 'Why it matters:'), ('whats_happening', "What's happening:"), ('the_big_picture', 'The big picture:'), ('go_deeper', 'Go deeper:'), ('icymi', 'ICYMI:'), ('one_fun_thing', 'One fun thing:'), ('custom', 'Custom')], default='whats_happening', max_length=30)),
                ('custom_lead', models.CharField(blank=True, help_text="Used when lead_style is 'Custom'", max_length=100)),
                ('headline', models.CharField(max_length=300)),
                ('body_text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='cards/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(default='Go deeper →', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Card',
                'verbose_name_plural': 'Content Cards',
                'ordering': ['sort_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Loudoun Proud', max_length=200)),
                ('tagline', models.CharField(default="Your weekly dose of what's happening in Ayrshire", max_length=300)),
                ('hero_headline', models.CharField(default='Welcome to Loudoun Proud', max_length=300)),
                ('hero_subheadline', models.TextField(blank=True, default="Ayrshire's community newsletter — local stories, events, and the people who make this place special.")),
                ('hero_video_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL for the hero video')),
                ('hero_image', models.ImageField(blank=True, help_text='Fallback hero background image', upload_to='hero/')),
                ('about_heading', models.CharField(default='About Loudoun Proud', max_length=300)),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, upload_to='about/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('newsletter_day', models.CharField(default='Friday', max_length=20)),
                ('meta_description', models.CharField(blank=True, default='Loudoun Proud — your weekly Ayrshire community newsletter covering Kilmarnock, Troon, Ayr, and beyond.', max_length=160)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
