# Generated by Django 5.2.11 on 2026-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcard',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature as the dominant story'),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='When this story was published (shown as timestamp)', null=True),
        ),
    ]
