# Generated by Django 5.2.11 on 2026-02-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentcard_is_featured_contentcard_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcard',
            name='exclude_from_most_read',
            field=models.BooleanField(default=False, help_text='Hide from Most Read lists (legal, sensitive, sponsored)'),
        ),
    ]
