# Generated by Django 5.2.11 on 2026-02-16 23:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique key used in template tags, e.g. 'leaderboard'", max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text="Human-readable location, e.g. 'Below lead story'", max_length=200)),
                ('width', models.PositiveIntegerField(help_text='Width in pixels')),
                ('height', models.PositiveIntegerField(help_text='Height in pixels')),
                ('is_responsive', models.BooleanField(default=False, help_text='Allow fluid sizing on mobile')),
                ('max_creatives', models.PositiveIntegerField(default=1, help_text='Maximum creatives in rotation pool')),
                ('rotation_strategy', models.CharField(choices=[('priority', 'Priority-first'), ('weighted', 'Weighted random'), ('random', 'Random'), ('sequential', 'Sequential')], default='priority', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Slot',
                'verbose_name_plural': 'Ad Slots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal reference name', max_length=200)),
                ('provider', models.CharField(choices=[('adsense', 'Google AdSense'), ('direct', 'Direct Sale'), ('house', 'House Ad'), ('sponsor', 'Sponsor')], default='house', max_length=20)),
                ('creative_type', models.CharField(choices=[('image', 'Image'), ('html', 'HTML / Script'), ('text', 'Text Only')], default='image', max_length=20)),
                ('markup', models.TextField(blank=True, help_text='HTML/JavaScript code (for AdSense or custom HTML creatives)')),
                ('image', models.ImageField(blank=True, help_text='Image file for direct/house/sponsor ads', upload_to='ads/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('target_url', models.URLField(blank=True, help_text='Click-through URL')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(help_text='When to stop showing this creative')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority (0–100)')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative weight for weighted rotation (1–100)')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='advertising.adslot')),
            ],
            options={
                'verbose_name': 'Ad Creative',
                'verbose_name_plural': 'Ad Creatives',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], default='impression', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='advertising.adcreative')),
            ],
            options={
                'verbose_name': 'Ad Impression',
                'verbose_name_plural': 'Ad Impressions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['creative', 'event_type', 'timestamp'], name='advertising_creativ_dfe407_idx')],
            },
        ),
    ]
