# Generated by Django 5.2.11 on 2026-02-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('250-500', '£250 – £500'), ('500-1000', '£500 – £1,000'), ('1000-2500', '£1,000 – £2,500'), ('2500+', '£2,500+')], max_length=20)),
                ('campaign_goal', models.CharField(blank=True, choices=[('awareness', 'Brand Awareness'), ('promotion', 'Promotion / Offer'), ('hiring', 'Hiring / Recruitment'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not visible to the enquirer.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertiser Lead',
                'verbose_name_plural': 'Advertiser Leads',
                'ordering': ['-created'],
            },
        ),
    ]
