# Generated by Django 5.2.11 on 2026-02-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='authors/')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('deck', models.CharField(blank=True, help_text='Standfirst / summary shown below the headline', max_length=500)),
                ('body_markdown', models.TextField(blank=True, verbose_name='Body (Markdown)')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('hero_image', models.ImageField(blank=True, upload_to='articles/')),
                ('hero_caption', models.CharField(blank=True, max_length=200)),
                ('hero_alt', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('news', 'News'), ('business', 'Business'), ('community', 'Community'), ('sport', 'Sport'), ('culture', 'Culture')], default='news', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publish date (or scheduled date)', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature as the lead story on the homepage')),
                ('is_sponsored', models.BooleanField(default=False)),
                ('sponsor_name', models.CharField(blank=True, max_length=200)),
                ('sponsor_url', models.URLField(blank=True)),
                ('exclude_from_most_read', models.BooleanField(default=False, help_text='Hide from Most Read lists (legal, sensitive, sponsored)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the homepage')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['sort_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='articles.article')),
            ],
            options={
                'verbose_name': 'Slug Redirect',
                'verbose_name_plural': 'Slug Redirects',
            },
        ),
    ]
