# Generated by Django 5.2.11 on 2026-02-16 23:40

from django.db import migrations
from django.utils.text import slugify


LEAD_TO_CATEGORY = {
    "why_it_matters": "news",
    "whats_happening": "news",
    "the_big_picture": "news",
    "go_deeper": "news",
    "icymi": "community",
    "one_fun_thing": "culture",
    "custom": "news",
}


def forward(apps, schema_editor):
    ContentCard = apps.get_model("core", "ContentCard")
    Article = apps.get_model("articles", "Article")

    for card in ContentCard.objects.all():
        # Build unique slug
        base_slug = slugify(card.headline)[:290] or "untitled"
        slug = base_slug
        n = 1
        while Article.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{n}"
            n += 1

        Article.objects.create(
            title=card.headline,
            slug=slug,
            deck=card.body_text[:500] if card.body_text else "",
            body_markdown=card.body_text or "",
            body_html=f"<p>{card.body_text}</p>" if card.body_text else "",
            hero_image=card.image.name if card.image else "",
            hero_alt=card.image_alt or "",
            category=LEAD_TO_CATEGORY.get(card.lead_style, "news"),
            status="published" if card.is_active else "draft",
            published_at=card.published_date,
            is_featured=card.is_featured,
            exclude_from_most_read=card.exclude_from_most_read,
            sort_order=card.sort_order,
        )


def backward(apps, schema_editor):
    Article = apps.get_model("articles", "Article")
    Article.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
