# Generated by Django 5.2.11 on 2026-02-16 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_migrate_content_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline_override',
            field=models.CharField(blank=True, help_text="Override the author byline (e.g. 'Staff Writer', 'From the newsroom')", max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive authors are hidden from listings but keep historical attribution'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_staff_writer',
            field=models.BooleanField(default=True, help_text='Staff writer vs external contributor', verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Ayrshire', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='role_title',
            field=models.CharField(blank=True, help_text='e.g. Editor, Contributor, Sports Reporter', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='author',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='author',
            name='x_url',
            field=models.URLField(blank=True, verbose_name='X / Twitter'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio — aim for 1–2 sentences'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Display name'),
        ),
    ]
