# Generated by Django 5.2.11 on 2026-02-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_byline_override_author_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section_lead',
            field=models.BooleanField(default=False, help_text='Feature as the lead story on its section page'),
        ),
        migrations.AddField(
            model_name='article',
            name='section_priority',
            field=models.IntegerField(default=0, help_text='Higher number = appears earlier on section page'),
        ),
    ]
