# Generated by Django 5.2.11 on 2026-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_section_lead_article_section_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feature_frame',
            field=models.BooleanField(default=False, help_text='Add subtle keyline frame to featured image (use sparingly)'),
        ),
        migrations.AddField(
            model_name='article',
            name='homepage_secondary',
            field=models.BooleanField(default=False, help_text='Show in the secondary authority band on the homepage'),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_priority',
            field=models.IntegerField(default=0, help_text='Higher number = appears earlier in the secondary band'),
        ),
    ]
