# Generated by Django 5.2.11 on 2026-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_feature_frame_article_homepage_secondary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('council_area', models.CharField(choices=[('east_ayrshire', 'East Ayrshire'), ('north_ayrshire', 'North Ayrshire'), ('south_ayrshire', 'South Ayrshire')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='SEO description for the town page')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order within council area')),
            ],
            options={
                'ordering': ['council_area', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='towns',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.town'),
        ),
    ]
