# Generated by Django 5.2.11 on 2026-02-17 09:12

from django.db import migrations


TOWNS = [
    # East Ayrshire
    ("kilmarnock", "Kilmarnock", "east_ayrshire", 1),
    ("kilmaurs", "Kilmaurs", "east_ayrshire", 2),
    ("stewarton", "Stewarton", "east_ayrshire", 3),
    ("hurlford", "Hurlford", "east_ayrshire", 4),
    ("galston", "Galston", "east_ayrshire", 5),
    ("newmilns", "Newmilns", "east_ayrshire", 6),
    ("darvel", "Darvel", "east_ayrshire", 7),
    ("mauchline", "Mauchline", "east_ayrshire", 8),
    ("auchinleck", "Auchinleck", "east_ayrshire", 9),
    ("cumnock", "Cumnock", "east_ayrshire", 10),
    # North Ayrshire
    ("irvine", "Irvine", "north_ayrshire", 1),
    ("kilwinning", "Kilwinning", "north_ayrshire", 2),
    ("ardrossan", "Ardrossan", "north_ayrshire", 3),
    ("stevenston", "Stevenston", "north_ayrshire", 4),
    # South Ayrshire
    ("ayr", "Ayr", "south_ayrshire", 1),
    ("prestwick", "Prestwick", "south_ayrshire", 2),
    ("troon", "Troon", "south_ayrshire", 3),
]


def seed_towns(apps, schema_editor):
    Town = apps.get_model("articles", "Town")
    for slug, name, council_area, sort_order in TOWNS:
        Town.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "council_area": council_area,
                "sort_order": sort_order,
            },
        )


def remove_towns(apps, schema_editor):
    Town = apps.get_model("articles", "Town")
    slugs = [slug for slug, *_ in TOWNS]
    Town.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_town_article_towns'),
    ]

    operations = [
        migrations.RunPython(seed_towns, remove_towns),
    ]
