# Generated by Django 5.2.11 on 2026-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_seed_towns'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Primary article image — used on cards and at the top of the article page', upload_to='articles/'),
        ),
    ]
