# Generated by Django 5.2.11 on 2026-02-17 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique identifier, e.g. rail_primary, footer_global', unique=True)),
                ('title', models.CharField(help_text='Headline copy', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Value proposition text')),
                ('cta_text', models.CharField(default='Subscribe', max_length=50)),
                ('incentive_text', models.CharField(blank=True, help_text="e.g. 'No spam. Unsubscribe anytime.'", max_length=200)),
                ('success_message', models.CharField(blank=True, default='Check your inbox to confirm your subscription.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('style', models.CharField(choices=[('compact', 'Compact (email + button)'), ('full', 'Full (headline + description + form)'), ('inline', 'Inline (horizontal bar)')], default='compact', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Placement',
                'verbose_name_plural': 'Newsletter Placements',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source_placement',
            field=models.CharField(blank=True, help_text='Placement key where this subscriber signed up', max_length=100),
        ),
        migrations.CreateModel(
            name='NewsletterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('submission', 'Submission'), ('confirmation', 'Confirmation')], max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='newsletter.newsletterplacement')),
            ],
            options={
                'verbose_name': 'Newsletter Event',
                'verbose_name_plural': 'Newsletter Events',
                'ordering': ['-created'],
            },
        ),
    ]
